import esbuild from "esbuild";
import process from "process";
import inlineWorkerPlugin from "esbuild-plugin-inline-worker";
import { wasmLoader } from "esbuild-plugin-wasm";
import { writeFileSync } from "fs";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/`;

const prod = process.argv.includes("production");
const generateMeta = process.argv.includes("--meta");

const workerBuildOptions = {
  bundle: true,
  platform: "browser",
  target: ["es2020"],
  format: "iife",

  charset: "utf8",

  minify: prod,
  treeShaking: true,
  legalComments: "none",
  sourcemap: false,

  plugins: [
    wasmLoader({ mode: "deferred" }),
  ],
};

const args = {
  banner: { js: banner },
  entryPoints: {
    main: "./src/main.ts",
    styles: "./src/styles.css",
  },
  bundle: true,

  external: [
    "obsidian",
    "electron",
    "react",
    "react-dom",
    "mathjax", 
    "@codemirror/autocomplete",
    "@codemirror/closebrackets",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/comment",
    "@codemirror/fold",
    "@codemirror/gutter",
    "@codemirror/highlight",
    "@codemirror/history",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/matchbrackets",
    "@codemirror/panel",
    "@codemirror/rangeset",
    "@codemirror/rectangular-selection",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/stream-parser",
    "@codemirror/text",
    "@codemirror/tooltip",
    "@codemirror/view",
    "@lezer/highlight",
  ],

  format: "cjs",
  target: "es2020",
  platform: "browser",
  charset: "utf8",

  outdir: ".",
  entryNames: "[name]",
  assetNames: "assets/[name]-[hash]",

  minify: prod,
  minifyIdentifiers: prod,
  minifySyntax: prod,
  minifyWhitespace: prod,
  treeShaking: true,
  legalComments: "none",

  drop: prod ? ["debugger"] : [],

  // DON’T inline wasm
  loader: {
    ".css": "css",
    ".wasm": "file",
  },

  plugins: [
    inlineWorkerPlugin(workerBuildOptions),
    wasmLoader({ mode: "deferred" }),
  ],
  logLevel: "info",
};

const result = await esbuild.build({
  ...args,
  metafile: generateMeta,
});

if (generateMeta && result.metafile) {
  writeFileSync("meta.json", JSON.stringify(result.metafile, null, 2));
  console.log("Built. metafile -> meta.json");
}