import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import inlineWorkerPlugin from "esbuild-plugin-inline-worker";
import { wasmLoader } from "esbuild-plugin-wasm";
import { writeFileSync } from "fs";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/`;

const prod = process.argv[2] === "production";

const args = {
  banner: { js: banner },
  entryPoints: {
    main: "./src/main.ts",
    styles: "./src/styles.css",
  },
  bundle: true,

  // CRITICAL: don’t ship these
  external: [
    "obsidian",
    "electron",
    "react",
    "react-dom",
    "mathjax", // harmless to leave here even if you uninstalled it
    "@codemirror/autocomplete",
    "@codemirror/closebrackets",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/comment",
    "@codemirror/fold",
    "@codemirror/gutter",
    "@codemirror/highlight",
    "@codemirror/history",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/matchbrackets",
    "@codemirror/panel",
    "@codemirror/rangeset",
    "@codemirror/rectangular-selection",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/stream-parser",
    "@codemirror/text",
    "@codemirror/tooltip",
    "@codemirror/view",
    "@lezer/highlight",
    ...builtins, // fs, path, etc.
  ],

  format: "cjs",
  target: "es2016",
  platform: "node",

  // Output to repo root (your current setup)
  outdir: ".",
  entryNames: "[name]",
  assetNames: "assets/[name]-[hash]",

  // Size & diagnostics
  minify: true,
  legalComments: "none",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  metafile: true, // <— so we can visualize

  // DON’T inline wasm
  loader: {
    ".css": "css",
    ".wasm": "file",
  },

  // Inline worker code, but keep wasm as FILE (not embedded)
  plugins: [
    inlineWorkerPlugin({
      bundle: true,
      target: ["es2016"],
      platform: "node",
      format: "cjs",
      plugins: [
        // ensure workers also emit wasm as a file
        wasmLoader({ mode: "deferred" }),
      ],
    }),
    // top-level wasm: emit as separate asset
    wasmLoader({ mode: "deferred" }),
  ],
  logLevel: "info",
};

const result = await esbuild.build(args).catch(() => process.exit(1));
// write metafile next to main.js
writeFileSync("meta.json", JSON.stringify(result.metafile, null, 2));
console.log("Built. metafile -> meta.json");
