$ErrorActionPreference = "Stop"

$projectRoot = Split-Path -Parent $PSScriptRoot

$generatedDirectory = Join-Path `
    $projectRoot `
    "src\generated"

$artifacts = @(
    @{
        Name = "PDF-to-SVG WASM"
        Source = "src\latexRender\pdfToHtml\pdfToSvgWasm.js"
        Output = "pdfToSvgWasm.payload.ts"
        ExportName = "pdfToSvgWasmGzipBase64"
    },

    @{
        Name = "PDFTeX worker"
        Source = "src\latexRender\compiler\swiftlatexpdftex\swiftlatexpdftex.worker.js"
        Output = "pdftexWorker.payload.ts"
        ExportName = "pdftexWorkerGzipBase64"
    },

    @{
        Name = "XeTeX worker"
        Source = "src\latexRender\compiler\swiftlatexxetex\swiftlatexxetex.worker.js"
        Output = "xetexWorker.payload.ts"
        ExportName = "xetexWorkerGzipBase64"
    },

    @{
        Name = "DVI worker"
        Source = "src\latexRender\compiler\swiftlatexxetex\swiftlatexdvipdfm.worker.js"
        Output = "dviWorker.payload.ts"
        ExportName = "dviWorkerGzipBase64"
    }
)

function Get-RelativePath {
    param(
        [Parameter(Mandatory)]
        [string] $BasePath,

        [Parameter(Mandatory)]
        [string] $TargetPath
    )

    $resolvedBasePath = [System.IO.Path]::GetFullPath($BasePath)
    $resolvedTargetPath = [System.IO.Path]::GetFullPath($TargetPath)

    if (-not $resolvedBasePath.EndsWith(
        [System.IO.Path]::DirectorySeparatorChar
    )) {
        $resolvedBasePath += [System.IO.Path]::DirectorySeparatorChar
    }

    $baseUri = [System.Uri]::new($resolvedBasePath)
    $targetUri = [System.Uri]::new($resolvedTargetPath)

    $relativeUri = $baseUri.MakeRelativeUri($targetUri)

    return [System.Uri]::UnescapeDataString(
        $relativeUri.ToString()
    ).Replace("/", [System.IO.Path]::DirectorySeparatorChar)
}

function Format-FileSize {
    param(
        [long] $Bytes
    )

    if ($Bytes -ge 1MB) {
        return "{0:N2} MB" -f ($Bytes / 1MB)
    }

    if ($Bytes -ge 1KB) {
        return "{0:N2} KB" -f ($Bytes / 1KB)
    }

    return "$Bytes bytes"
}

function Compress-ToGzip {
    param(
        [byte[]] $InputBytes
    )

    $outputStream = [System.IO.MemoryStream]::new()

    try {
        $gzipStream = [System.IO.Compression.GZipStream]::new(
            $outputStream,
            [System.IO.Compression.CompressionLevel]::Optimal,
            $true
        )

        try {
            $gzipStream.Write(
                $InputBytes,
                0,
                $InputBytes.Length
            )
        }
        finally {
            $gzipStream.Dispose()
        }

        return $outputStream.ToArray()
    }
    finally {
        $outputStream.Dispose()
    }
}

function Write-PayloadFile {
    param(
        [string] $ArtifactName,
        [string] $SourcePath,
        [string] $OutputPath,
        [string] $ExportName
    )

    if (-not (Test-Path $SourcePath)) {
        throw "Source for '$ArtifactName' was not found: $SourcePath"
    }

    Write-Host "Compressing $ArtifactName..."

    $sourceBytes = [System.IO.File]::ReadAllBytes(
        $SourcePath
    )

    $compressedBytes = Compress-ToGzip `
        -InputBytes $sourceBytes

    $base64 = [Convert]::ToBase64String(
        $compressedBytes
    )

    $sourceRelativePath = (
        Get-RelativePath `
            -BasePath $projectRoot `
            -TargetPath $SourcePath
    ).Replace("\", "/")

    $generatedContent = @"
// This file is generated automatically.
// Do not edit this file manually.
//
// Original source:
// $sourceRelativePath
//
// Regenerate with:
// npm run generate:payloads

export const $ExportName = "$base64";
"@

    [System.IO.File]::WriteAllText(
        $OutputPath,
        $generatedContent,
        [System.Text.UTF8Encoding]::new($false)
    )

    $base64Bytes = [System.Text.Encoding]::ASCII.GetByteCount(
        $base64
    )

    $gzipRatio = (
        $compressedBytes.Length /
        $sourceBytes.Length
    ) * 100

    $payloadRatio = (
        $base64Bytes /
        $sourceBytes.Length
    ) * 100

    Write-Host "  Source:  $(Format-FileSize $sourceBytes.Length)"
    Write-Host "  Gzip:    $(Format-FileSize $compressedBytes.Length)"
    Write-Host "  Base64:  $(Format-FileSize $base64Bytes)"
    Write-Host ("  Gzip ratio:   {0:N1}%" -f $gzipRatio)
    Write-Host ("  Payload ratio:{0:N1}%" -f $payloadRatio)
    Write-Host "  Output:  $OutputPath"
    Write-Host ""
}

if (-not (Test-Path $generatedDirectory)) {
    New-Item `
        -ItemType Directory `
        -Path $generatedDirectory `
        -Force | Out-Null
}

foreach ($artifact in $artifacts) {
    $sourcePath = Join-Path `
        $projectRoot `
        $artifact.Source

    $outputPath = Join-Path `
        $generatedDirectory `
        $artifact.Output

    Write-PayloadFile `
        -ArtifactName $artifact.Name `
        -SourcePath $sourcePath `
        -OutputPath $outputPath `
        -ExportName $artifact.ExportName
}

Write-Host "All compressed payloads were generated successfully."